name: SonarQube analysis

on:
  push:
    branches: [$default-branch, $protected-branches]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

   
