name: yaml-test-suite Repository Testing

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: nginx-latest

    steps:
    - uses: actions/checkout@v2
    - run: make test
    # - uses: mxschmitt/action-tmate@v3